In [9]:
#webcam on

In [6]:
import cv2
from pop import Util

In [ ]:
Util.enable_imshow()

cam = Util.gstrmer(width=640,height=480)
camera =cv2.VideoCapture(cam,cv2.CAP_GSTREAMER)
if not camera.isOpened():
    print("NOT found camera")
    
while True:
    ret,frame = camera.read()
    cv2.imshow("soda",frame)
camera.release()
cv2.destoryAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

In [ ]:
# capture image 

In [5]:
import cv2
import time
from pop import Util

In [12]:
Util.enable_imshow()

cam = Util.gstrmer(width=640,height=480)
camera =cv2.VideoCapture(cam,cv2.CAP_GSTREAMER)
img_counter=0
interval =10
if not camera.isOpened():
    print("NOT found camera")
    
while True:
    current_time = int(time.time())
    ret,frame = camera.read()
    cv2.imshow("soda",frame)
    if current_time % interval == 0:
        img_name="image/captured_img_{}.png".format(img_counter)
        cv2.imwrite(img_name,frame)
        print("{}written!".format(img_name))
        img_counter+=1
        if(img_counter == 20):
            break
        time.sleep(1)
    
camera.release()
cv2.destoryAllWindows()

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

image/captured_img_0.pngwritten!
image/captured_img_1.pngwritten!
image/captured_img_2.pngwritten!
image/captured_img_3.pngwritten!
image/captured_img_4.pngwritten!
image/captured_img_5.pngwritten!
image/captured_img_6.pngwritten!
image/captured_img_7.pngwritten!
image/captured_img_8.pngwritten!
image/captured_img_9.pngwritten!
image/captured_img_10.pngwritten!
image/captured_img_11.pngwritten!
image/captured_img_12.pngwritten!
image/captured_img_13.pngwritten!
image/captured_img_14.pngwritten!
image/captured_img_15.pngwritten!
image/captured_img_16.pngwritten!
image/captured_img_17.pngwritten!
image/captured_img_18.pngwritten!
image/captured_img_19.pngwritten!


AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

In [ ]:
# find camera intrinsic parameters ! 

In [1]:
import numpy as np
import cv2

In [2]:

# 체스판 이미지에서 코너를 검출하기 위한 설정
CHESSBOARD_SIZE = (8, 5)
CHESSBOARD_FLAGS = cv2.CALIB_CB_ADAPTIVE_THRESH | cv2.CALIB_CB_NORMALIZE_IMAGE

# 카메라 캘리브레이션을 위한 샘플 이미지 경로
CALIBRATION_IMAGES = ['image/captured_img_0.png','image/captured_img_1.png','image/captured_img_2.png','image/captured_img_3.png','image/captured_img_4.png',
                      'image/captured_img_5.png','image/captured_img_6.png','image/captured_img_7.png','image/captured_img_8.png','image/captured_img_9.png',
                      'image/captured_img_10.png','image/captured_img_11.png','image/captured_img_12.png','image/captured_img_13.png','image/captured_img_14.png',
                      'image/captured_img_15.png','image/captured_img_16.png','image/captured_img_17.png','image/captured_img_18.png','image/captured_img_19.png']

# 체스판 코너를 검출하기 위한 객체 생성
chessboard_criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# 체스판 코너를 검출하기 위한 함수
def find_chessboard_corners(image_path):
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, corners = cv2.findChessboardCorners(gray, CHESSBOARD_SIZE, None, CHESSBOARD_FLAGS)
    if ret:
        corners = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), chessboard_criteria)
    return ret, corners

# 캘리브레이션에 필요한 체스판 코너 검출 결과
object_points = []
image_points = []

# 체스판 코너 검출
for image_path in CALIBRATION_IMAGES:
    ret, corners = find_chessboard_corners(image_path)
    if ret:
        object_points.append(np.zeros((CHESSBOARD_SIZE[0] * CHESSBOARD_SIZE[1], 3), np.float32))
        object_points[-1][:, :2] = np.mgrid[0:CHESSBOARD_SIZE[0], 0:CHESSBOARD_SIZE[1]].T.reshape(-1, 2)
        image_points.append(corners)

# 카메라 캘리브레이션
image_size = cv2.imread(CALIBRATION_IMAGES[0]).shape[:2]
ret, camera_matrix, distortion_coefficients, rotation_vectors, translation_vectors = cv2.calibrateCamera(
    object_points, image_points, image_size, None, None
)
print("Camera matrix:\n", camera_matrix)
print("Distortion coefficients:\n", distortion_coefficients)
np.save("intrinsic_parameters/camera_matrix.npy",camera_matrix)
np.save("intrinsic_parameters/distortion_coefficients.npy",distortion_coefficients)
# 결과 출력


Camera matrix:
 [[497.73103339   0.         236.69169791]
 [  0.         665.11213666 274.63204925]
 [  0.           0.           1.        ]]
Distortion coefficients:
 [[-0.44148389  0.20830902 -0.00840704  0.02274212 -0.10547549]]


In [3]:
import cv2
import numpy as np
from pop import Util

In [4]:
Util.enable_imshow()

cam = Util.gstrmer(width=640,height=480)
camera =cv2.VideoCapture(cam,cv2.CAP_GSTREAMER)

img_counter=0
interval =10
camera_matrix_file="intrinsic_parameters/camera_matrix.npy"
dist_coeffs_file = "intrinsic_parameters/distortion_coefficients.npy"

camera_matrix=np.load(camera_matrix_file)
dist_coeffs=np.load(dist_coeffs_file)
print("camera_matrix",camera_matrix)
print("dist_coeffs",dist_coeffs)
if not camera.isOpened():
    print("NOT found camera")
    
while True:
    ret,frame = camera.read()
    undistorted=cv2.undistort(frame,camera_matrix,dist_coeffs)
    cv2.imshow("soda",undistorted)
    
camera.release()
cv2.destoryAllWindows()

camera_matrix [[497.73103339   0.         236.69169791]
 [  0.         665.11213666 274.63204925]
 [  0.           0.           1.        ]]
dist_coeffs [[-0.44148389  0.20830902 -0.00840704  0.02274212 -0.10547549]]


Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

KeyboardInterrupt: 

In [6]:
import cv2
import numpy as np
from pop import Util

In [8]:
Util.enable_imshow()

# 이미지 파일 경로
IMAGE_PATH = "image/captured_img_17.png"

# 내부 파라미터 파일 경로
CAMERA_MATRIX_PATH = "intrinsic_parameters/camera_matrix.npy"
DISTORTION_COEFFICIENTS_PATH = "intrinsic_parameters/distortion_coefficients.npy"

# 이미지 불러오기
original_image = cv2.imread(IMAGE_PATH)

# 내부 파라미터 로드
camera_matrix = np.load(CAMERA_MATRIX_PATH)
distortion_coefficients = np.load(DISTORTION_COEFFICIENTS_PATH)

# 이미지 캘리브레이션
undistorted_image = cv2.undistort(original_image, camera_matrix, distortion_coefficients)

cv2.imwrite("undistorted_Image.png",undistorted_image)

cv2.imshow("Original Image",original_image)
cv2.imshow("undistorted_Image",undistorted_image)
# 해상도 출력
print("Original image resolution:", original_image.shape[:2])
print("Undistorted image resolution:", undistorted_image.shape[:2])

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Image(value=b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x02\x01\x0…

Original image resolution: (480, 640)
Undistorted image resolution: (480, 640)
